import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'index',
    'quickstart',
    'cli-reference',
    'doctor',
    'local-server',
    'webhooks',
    'development',
    {
      type: 'category',
      label: 'API Reference',
      link: {
        type: 'generated-index',
        title: 'API Reference',
        slug: '/api',
      },
      items: [{type: 'autogenerated', dirName: 'api'}],
    },
  ],
};

export default sidebars;
